services:
  dev:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.js:/app/vite.config.js
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
